name: CI/CD build and publish

on:
  push: 
    branches:
      - develop
      - '*'

  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

env: 
  REGISTRY: "personal-registryhw4"
  IMAGE_NAME: "python_websitev1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup TAG
        shell: bash
        run: |
          if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
          else
          echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build app into Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG}} .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

